server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:8082/
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: http://localhost:8083/
          predicates:
            - Path=/order/**
